version: '3'

services:
  grafana:
    container_name: pirantos-grafana
    image: grafana/grafana:7.5.7
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/grafana
