version: '3'

services:
  mysql:
    container_name: pirantos-mysql
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always
